### ISSUE TITLE
ошибка из за фабрик модов майнкрафт 

### ISSUE THREAD

**Issue by taoke025** [Kamikaze94/WolfHUD#983]
запускаю майнкрафт но появляется окно ошибки с текстом ниже:
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'Minecraft' (minecraft) 1.16.5 with version 1.20.1.
	 - Replace 'Java HotSpot(TM) 64-Bit Server VM' (java) 8 with version 17 or later.
	 - Replace mod 'Sodium' (sodium) 0.5.11+mc1.20.1 with version 0.5.10 or version 0.5.11 that is compatible with:
		 - minecraft, version 1.20.1
		 - indium, any version
	 - Replace mod 'Dynamic FPS' (dynamic_fps) 3.6.3 with any version that is compatible with:
		 - fabricloader 0.15.7
		 - minecraft, version 1.20.1
	 - Replace mod 'Indium' (indium) 1.0.27+mc1.20.1 with any version that is compatible with:
		 - minecraft, version 1.20.1
		 - sodium, version 0.5.10 or version 0.5.11
More details:
	 - Mod 'Architectury' (architectury) 9.2.14 requires any 1.20.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Fabric API' (fabric-api) 0.92.2+1.20.1 requires version 17 or later of 'Java HotSpot(TM) 64-Bit Server VM' (java), but only the wrong version is present: 8!
	 - Mod 'Fabric API' (fabric-api) 0.92.2+1.20.1 requires any version between 1.20 (inclusive) and 1.20.2- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Cloth Config v11' (cloth-config) 11.1.118 requires version 1.20- or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Continuity' (continuity) 3.0.0-beta.5+1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Dynamic FPS' (dynamic_fps) 3.6.3 requires version 0.15.10 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.15.7!
	 - Mod 'Dynamic FPS' (dynamic_fps) 3.6.3 requires version 1.20.0, version 1.20.1, version 1.20.2, version 1.20.3 or version 1.20.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'FerriteCore' (ferritecore) 6.0.1 requires any version between 1.20 (inclusive) and 1.21 (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Indium' (indium) 1.0.27+mc1.20.1 requires any version between 1.20.1 (inclusive) and 1.21- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Indium' (indium) 1.0.27+mc1.20.1 requires version 0.5.3 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.11+mc1.20.1!
	 - Mod 'Iris' (iris) 1.7.2+mc1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Sodium' (sodium) 0.5.11+mc1.20.1 requires version 1.20.1 of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Sodium' (sodium) 0.5.11+mc1.20.1 is incompatible with version 1.0.28 or earlier of mod 'Indium' (indium), but a matching version is present: 1.0.27+mc1.20.1!
	 - Mod 'Krypton' (krypton) 0.2.3 requires any 1.20.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'LambDynamicLights' (lambdynlights) 2.3.1+1.20.1 requires any version between 1.20 (inclusive) and 1.21- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'LambDynamicLights' (lambdynlights) 2.3.1+1.20.1 requires version 17 or later of 'Java HotSpot(TM) 64-Bit Server VM' (java), but only the wrong version is present: 8!
	 - Mod 'SpruceUI' (spruceui) 5.0.0+1.20 requires version 1.20 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'SpruceUI' (spruceui) 5.0.0+1.20 requires version 17 or later of 'Java HotSpot(TM) 64-Bit Server VM' (java), but only the wrong version is present: 8!
	 - Mod 'LazyDFU' (lazydfu) 0.1.3 requires version 1.19 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Mod Menu' (modmenu) 7.2.2 requires version 1.19.4- or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Sodium Extra' (sodium-extra) 0.5.4+mc1.20.1-build.115 requires version 1.20.1 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'CaffeineConfig' (caffeineconfig) 1.3.0+1.17 requires version 16 or later of 'Java HotSpot(TM) 64-Bit Server VM' (java), but only the wrong version is present: 8!
	 - Mod 'Fabric Command API (v2)' (fabric-command-api-v2) 2.2.13+1802ada577 requires any version after 1.19-alpha.22.11.a of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Fabric Convention Tags' (fabric-convention-tags-v1) 1.5.5+1802ada577 requires version 1.18.2 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Fabric Sound API (v1)' (fabric-sound-api-v1) 1.0.13+1802ada577 requires version 1.19.2 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Pride Lib' (pride) 1.2.0+1.19.4 requires version 1.19.4 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Sk1m1kl** [comment]
????????????????????????????????????????????????????????????????????????????????
